// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v5.29.3
// source: picture/v1/picture.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationPictureDeletePicture = "/api.picture.v1.Picture/DeletePicture"
const OperationPictureGetPictureById = "/api.picture.v1.Picture/GetPictureById"
const OperationPictureListPictureByPage = "/api.picture.v1.Picture/ListPictureByPage"
const OperationPictureUpdatePicture = "/api.picture.v1.Picture/UpdatePicture"
const OperationPictureUploadPicture = "/api.picture.v1.Picture/UploadPicture"

type PictureHTTPServer interface {
	// DeletePicture 删除图片
	DeletePicture(context.Context, *DeletePictureRequest) (*DeletePictureReply, error)
	// GetPictureById 根据 ID 获取图片
	GetPictureById(context.Context, *GetPictureByIdRequest) (*GetPictureByIdReply, error)
	// ListPictureByPage 分页查询图片列表
	ListPictureByPage(context.Context, *ListPictureByPageRequest) (*ListPictureByPageReply, error)
	// UpdatePicture 更新图片信息
	UpdatePicture(context.Context, *UpdatePictureRequest) (*UpdatePictureReply, error)
	// UploadPicture 上传图片
	UploadPicture(context.Context, *UploadPictureRequest) (*UploadPictureReply, error)
}

func RegisterPictureHTTPServer(s *http.Server, srv PictureHTTPServer) {
	r := s.Route("/")
	r.POST("/api/picture/upload", _Picture_UploadPicture0_HTTP_Handler(srv))
	r.GET("/api/picture/get/{id}", _Picture_GetPictureById0_HTTP_Handler(srv))
	r.POST("/api/picture/list/page", _Picture_ListPictureByPage0_HTTP_Handler(srv))
	r.POST("/api/picture/delete", _Picture_DeletePicture0_HTTP_Handler(srv))
	r.POST("/api/picture/update", _Picture_UpdatePicture0_HTTP_Handler(srv))
}

func _Picture_UploadPicture0_HTTP_Handler(srv PictureHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UploadPictureRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPictureUploadPicture)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UploadPicture(ctx, req.(*UploadPictureRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UploadPictureReply)
		return ctx.Result(200, reply)
	}
}

func _Picture_GetPictureById0_HTTP_Handler(srv PictureHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPictureByIdRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPictureGetPictureById)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPictureById(ctx, req.(*GetPictureByIdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetPictureByIdReply)
		return ctx.Result(200, reply)
	}
}

func _Picture_ListPictureByPage0_HTTP_Handler(srv PictureHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListPictureByPageRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPictureListPictureByPage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListPictureByPage(ctx, req.(*ListPictureByPageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListPictureByPageReply)
		return ctx.Result(200, reply)
	}
}

func _Picture_DeletePicture0_HTTP_Handler(srv PictureHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeletePictureRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPictureDeletePicture)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeletePicture(ctx, req.(*DeletePictureRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeletePictureReply)
		return ctx.Result(200, reply)
	}
}

func _Picture_UpdatePicture0_HTTP_Handler(srv PictureHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdatePictureRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPictureUpdatePicture)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdatePicture(ctx, req.(*UpdatePictureRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdatePictureReply)
		return ctx.Result(200, reply)
	}
}

type PictureHTTPClient interface {
	// DeletePicture 删除图片
	DeletePicture(ctx context.Context, req *DeletePictureRequest, opts ...http.CallOption) (rsp *DeletePictureReply, err error)
	// GetPictureById 根据 ID 获取图片
	GetPictureById(ctx context.Context, req *GetPictureByIdRequest, opts ...http.CallOption) (rsp *GetPictureByIdReply, err error)
	// ListPictureByPage 分页查询图片列表
	ListPictureByPage(ctx context.Context, req *ListPictureByPageRequest, opts ...http.CallOption) (rsp *ListPictureByPageReply, err error)
	// UpdatePicture 更新图片信息
	UpdatePicture(ctx context.Context, req *UpdatePictureRequest, opts ...http.CallOption) (rsp *UpdatePictureReply, err error)
	// UploadPicture 上传图片
	UploadPicture(ctx context.Context, req *UploadPictureRequest, opts ...http.CallOption) (rsp *UploadPictureReply, err error)
}

type PictureHTTPClientImpl struct {
	cc *http.Client
}

func NewPictureHTTPClient(client *http.Client) PictureHTTPClient {
	return &PictureHTTPClientImpl{client}
}

// DeletePicture 删除图片
func (c *PictureHTTPClientImpl) DeletePicture(ctx context.Context, in *DeletePictureRequest, opts ...http.CallOption) (*DeletePictureReply, error) {
	var out DeletePictureReply
	pattern := "/api/picture/delete"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPictureDeletePicture))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetPictureById 根据 ID 获取图片
func (c *PictureHTTPClientImpl) GetPictureById(ctx context.Context, in *GetPictureByIdRequest, opts ...http.CallOption) (*GetPictureByIdReply, error) {
	var out GetPictureByIdReply
	pattern := "/api/picture/get/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationPictureGetPictureById))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListPictureByPage 分页查询图片列表
func (c *PictureHTTPClientImpl) ListPictureByPage(ctx context.Context, in *ListPictureByPageRequest, opts ...http.CallOption) (*ListPictureByPageReply, error) {
	var out ListPictureByPageReply
	pattern := "/api/picture/list/page"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPictureListPictureByPage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdatePicture 更新图片信息
func (c *PictureHTTPClientImpl) UpdatePicture(ctx context.Context, in *UpdatePictureRequest, opts ...http.CallOption) (*UpdatePictureReply, error) {
	var out UpdatePictureReply
	pattern := "/api/picture/update"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPictureUpdatePicture))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UploadPicture 上传图片
func (c *PictureHTTPClientImpl) UploadPicture(ctx context.Context, in *UploadPictureRequest, opts ...http.CallOption) (*UploadPictureReply, error) {
	var out UploadPictureReply
	pattern := "/api/picture/upload"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPictureUploadPicture))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
