// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: picture/v1/picture.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Picture_UploadPicture_FullMethodName         = "/api.picture.v1.Picture/UploadPicture"
	Picture_GetPictureById_FullMethodName        = "/api.picture.v1.Picture/GetPictureById"
	Picture_ListPictureByPage_FullMethodName     = "/api.picture.v1.Picture/ListPictureByPage"
	Picture_DeletePicture_FullMethodName         = "/api.picture.v1.Picture/DeletePicture"
	Picture_UpdatePicture_FullMethodName         = "/api.picture.v1.Picture/UpdatePicture"
	Picture_EditPicture_FullMethodName           = "/api.picture.v1.Picture/EditPicture"
	Picture_GetPictureVOById_FullMethodName      = "/api.picture.v1.Picture/GetPictureVOById"
	Picture_ListPictureVOByPage_FullMethodName   = "/api.picture.v1.Picture/ListPictureVOByPage"
	Picture_GetPictureTagCategory_FullMethodName = "/api.picture.v1.Picture/GetPictureTagCategory"
)

// PictureClient is the client API for Picture service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PictureClient interface {
	// 上传图片
	UploadPicture(ctx context.Context, in *UploadPictureRequest, opts ...grpc.CallOption) (*UploadPictureReply, error)
	// 根据 ID 获取图片
	GetPictureById(ctx context.Context, in *GetPictureByIdRequest, opts ...grpc.CallOption) (*GetPictureByIdReply, error)
	// 分页查询图片列表
	ListPictureByPage(ctx context.Context, in *ListPictureByPageRequest, opts ...grpc.CallOption) (*ListPictureByPageReply, error)
	// 删除图片
	DeletePicture(ctx context.Context, in *DeletePictureRequest, opts ...grpc.CallOption) (*DeletePictureReply, error)
	// 更新图片信息（管理员）
	UpdatePicture(ctx context.Context, in *UpdatePictureRequest, opts ...grpc.CallOption) (*UpdatePictureReply, error)
	// 编辑图片（用户）
	EditPicture(ctx context.Context, in *EditPictureRequest, opts ...grpc.CallOption) (*EditPictureReply, error)
	// 获取图片 VO（脱敏）
	GetPictureVOById(ctx context.Context, in *GetPictureVOByIdRequest, opts ...grpc.CallOption) (*GetPictureVOByIdReply, error)
	// 分页获取图片列表 VO（脱敏）
	ListPictureVOByPage(ctx context.Context, in *ListPictureVOByPageRequest, opts ...grpc.CallOption) (*ListPictureVOByPageReply, error)
	// 获取标签和分类
	GetPictureTagCategory(ctx context.Context, in *GetPictureTagCategoryRequest, opts ...grpc.CallOption) (*GetPictureTagCategoryReply, error)
}

type pictureClient struct {
	cc grpc.ClientConnInterface
}

func NewPictureClient(cc grpc.ClientConnInterface) PictureClient {
	return &pictureClient{cc}
}

func (c *pictureClient) UploadPicture(ctx context.Context, in *UploadPictureRequest, opts ...grpc.CallOption) (*UploadPictureReply, error) {
	out := new(UploadPictureReply)
	err := c.cc.Invoke(ctx, Picture_UploadPicture_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pictureClient) GetPictureById(ctx context.Context, in *GetPictureByIdRequest, opts ...grpc.CallOption) (*GetPictureByIdReply, error) {
	out := new(GetPictureByIdReply)
	err := c.cc.Invoke(ctx, Picture_GetPictureById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pictureClient) ListPictureByPage(ctx context.Context, in *ListPictureByPageRequest, opts ...grpc.CallOption) (*ListPictureByPageReply, error) {
	out := new(ListPictureByPageReply)
	err := c.cc.Invoke(ctx, Picture_ListPictureByPage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pictureClient) DeletePicture(ctx context.Context, in *DeletePictureRequest, opts ...grpc.CallOption) (*DeletePictureReply, error) {
	out := new(DeletePictureReply)
	err := c.cc.Invoke(ctx, Picture_DeletePicture_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pictureClient) UpdatePicture(ctx context.Context, in *UpdatePictureRequest, opts ...grpc.CallOption) (*UpdatePictureReply, error) {
	out := new(UpdatePictureReply)
	err := c.cc.Invoke(ctx, Picture_UpdatePicture_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pictureClient) EditPicture(ctx context.Context, in *EditPictureRequest, opts ...grpc.CallOption) (*EditPictureReply, error) {
	out := new(EditPictureReply)
	err := c.cc.Invoke(ctx, Picture_EditPicture_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pictureClient) GetPictureVOById(ctx context.Context, in *GetPictureVOByIdRequest, opts ...grpc.CallOption) (*GetPictureVOByIdReply, error) {
	out := new(GetPictureVOByIdReply)
	err := c.cc.Invoke(ctx, Picture_GetPictureVOById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pictureClient) ListPictureVOByPage(ctx context.Context, in *ListPictureVOByPageRequest, opts ...grpc.CallOption) (*ListPictureVOByPageReply, error) {
	out := new(ListPictureVOByPageReply)
	err := c.cc.Invoke(ctx, Picture_ListPictureVOByPage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pictureClient) GetPictureTagCategory(ctx context.Context, in *GetPictureTagCategoryRequest, opts ...grpc.CallOption) (*GetPictureTagCategoryReply, error) {
	out := new(GetPictureTagCategoryReply)
	err := c.cc.Invoke(ctx, Picture_GetPictureTagCategory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PictureServer is the server API for Picture service.
// All implementations must embed UnimplementedPictureServer
// for forward compatibility
type PictureServer interface {
	// 上传图片
	UploadPicture(context.Context, *UploadPictureRequest) (*UploadPictureReply, error)
	// 根据 ID 获取图片
	GetPictureById(context.Context, *GetPictureByIdRequest) (*GetPictureByIdReply, error)
	// 分页查询图片列表
	ListPictureByPage(context.Context, *ListPictureByPageRequest) (*ListPictureByPageReply, error)
	// 删除图片
	DeletePicture(context.Context, *DeletePictureRequest) (*DeletePictureReply, error)
	// 更新图片信息（管理员）
	UpdatePicture(context.Context, *UpdatePictureRequest) (*UpdatePictureReply, error)
	// 编辑图片（用户）
	EditPicture(context.Context, *EditPictureRequest) (*EditPictureReply, error)
	// 获取图片 VO（脱敏）
	GetPictureVOById(context.Context, *GetPictureVOByIdRequest) (*GetPictureVOByIdReply, error)
	// 分页获取图片列表 VO（脱敏）
	ListPictureVOByPage(context.Context, *ListPictureVOByPageRequest) (*ListPictureVOByPageReply, error)
	// 获取标签和分类
	GetPictureTagCategory(context.Context, *GetPictureTagCategoryRequest) (*GetPictureTagCategoryReply, error)
	mustEmbedUnimplementedPictureServer()
}

// UnimplementedPictureServer must be embedded to have forward compatible implementations.
type UnimplementedPictureServer struct {
}

func (UnimplementedPictureServer) UploadPicture(context.Context, *UploadPictureRequest) (*UploadPictureReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadPicture not implemented")
}
func (UnimplementedPictureServer) GetPictureById(context.Context, *GetPictureByIdRequest) (*GetPictureByIdReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPictureById not implemented")
}
func (UnimplementedPictureServer) ListPictureByPage(context.Context, *ListPictureByPageRequest) (*ListPictureByPageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPictureByPage not implemented")
}
func (UnimplementedPictureServer) DeletePicture(context.Context, *DeletePictureRequest) (*DeletePictureReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePicture not implemented")
}
func (UnimplementedPictureServer) UpdatePicture(context.Context, *UpdatePictureRequest) (*UpdatePictureReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePicture not implemented")
}
func (UnimplementedPictureServer) EditPicture(context.Context, *EditPictureRequest) (*EditPictureReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditPicture not implemented")
}
func (UnimplementedPictureServer) GetPictureVOById(context.Context, *GetPictureVOByIdRequest) (*GetPictureVOByIdReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPictureVOById not implemented")
}
func (UnimplementedPictureServer) ListPictureVOByPage(context.Context, *ListPictureVOByPageRequest) (*ListPictureVOByPageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPictureVOByPage not implemented")
}
func (UnimplementedPictureServer) GetPictureTagCategory(context.Context, *GetPictureTagCategoryRequest) (*GetPictureTagCategoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPictureTagCategory not implemented")
}
func (UnimplementedPictureServer) mustEmbedUnimplementedPictureServer() {}

// UnsafePictureServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PictureServer will
// result in compilation errors.
type UnsafePictureServer interface {
	mustEmbedUnimplementedPictureServer()
}

func RegisterPictureServer(s grpc.ServiceRegistrar, srv PictureServer) {
	s.RegisterService(&Picture_ServiceDesc, srv)
}

func _Picture_UploadPicture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadPictureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PictureServer).UploadPicture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Picture_UploadPicture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PictureServer).UploadPicture(ctx, req.(*UploadPictureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Picture_GetPictureById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPictureByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PictureServer).GetPictureById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Picture_GetPictureById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PictureServer).GetPictureById(ctx, req.(*GetPictureByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Picture_ListPictureByPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPictureByPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PictureServer).ListPictureByPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Picture_ListPictureByPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PictureServer).ListPictureByPage(ctx, req.(*ListPictureByPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Picture_DeletePicture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePictureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PictureServer).DeletePicture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Picture_DeletePicture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PictureServer).DeletePicture(ctx, req.(*DeletePictureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Picture_UpdatePicture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePictureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PictureServer).UpdatePicture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Picture_UpdatePicture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PictureServer).UpdatePicture(ctx, req.(*UpdatePictureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Picture_EditPicture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditPictureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PictureServer).EditPicture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Picture_EditPicture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PictureServer).EditPicture(ctx, req.(*EditPictureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Picture_GetPictureVOById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPictureVOByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PictureServer).GetPictureVOById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Picture_GetPictureVOById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PictureServer).GetPictureVOById(ctx, req.(*GetPictureVOByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Picture_ListPictureVOByPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPictureVOByPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PictureServer).ListPictureVOByPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Picture_ListPictureVOByPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PictureServer).ListPictureVOByPage(ctx, req.(*ListPictureVOByPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Picture_GetPictureTagCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPictureTagCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PictureServer).GetPictureTagCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Picture_GetPictureTagCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PictureServer).GetPictureTagCategory(ctx, req.(*GetPictureTagCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Picture_ServiceDesc is the grpc.ServiceDesc for Picture service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Picture_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.picture.v1.Picture",
	HandlerType: (*PictureServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadPicture",
			Handler:    _Picture_UploadPicture_Handler,
		},
		{
			MethodName: "GetPictureById",
			Handler:    _Picture_GetPictureById_Handler,
		},
		{
			MethodName: "ListPictureByPage",
			Handler:    _Picture_ListPictureByPage_Handler,
		},
		{
			MethodName: "DeletePicture",
			Handler:    _Picture_DeletePicture_Handler,
		},
		{
			MethodName: "UpdatePicture",
			Handler:    _Picture_UpdatePicture_Handler,
		},
		{
			MethodName: "EditPicture",
			Handler:    _Picture_EditPicture_Handler,
		},
		{
			MethodName: "GetPictureVOById",
			Handler:    _Picture_GetPictureVOById_Handler,
		},
		{
			MethodName: "ListPictureVOByPage",
			Handler:    _Picture_ListPictureVOByPage_Handler,
		},
		{
			MethodName: "GetPictureTagCategory",
			Handler:    _Picture_GetPictureTagCategory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "picture/v1/picture.proto",
}
