// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: user/v1/error_reason.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	// 参数错误
	ErrorReason_PARAMS_ERROR ErrorReason = 0
	// 账号过短
	ErrorReason_ACCOUNT_TOO_SHORT ErrorReason = 1
	// 密码过短
	ErrorReason_PASSWORD_TOO_SHORT ErrorReason = 2
	// 密码不一致
	ErrorReason_PASSWORD_NOT_MATCH ErrorReason = 3
	// 账号重复
	ErrorReason_ACCOUNT_DUPLICATE ErrorReason = 4
	// 系统错误
	ErrorReason_SYSTEM_ERROR ErrorReason = 5
	// 用户不存在或密码错误
	ErrorReason_USER_NOT_EXIST_OR_PASSWORD_ERROR ErrorReason = 6
	// 账号错误
	ErrorReason_ACCOUNT_ERROR ErrorReason = 7
	// 密码错误
	ErrorReason_PASSWORD_ERROR ErrorReason = 8
	// 未登录
	ErrorReason_NOT_LOGIN_ERROR ErrorReason = 9
	// Token 无效
	ErrorReason_INVALID_TOKEN ErrorReason = 10
	// 用户不存在
	ErrorReason_USER_NOT_FOUND ErrorReason = 11
	// 无权限
	ErrorReason_NO_AUTH_ERROR ErrorReason = 12
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:  "PARAMS_ERROR",
		1:  "ACCOUNT_TOO_SHORT",
		2:  "PASSWORD_TOO_SHORT",
		3:  "PASSWORD_NOT_MATCH",
		4:  "ACCOUNT_DUPLICATE",
		5:  "SYSTEM_ERROR",
		6:  "USER_NOT_EXIST_OR_PASSWORD_ERROR",
		7:  "ACCOUNT_ERROR",
		8:  "PASSWORD_ERROR",
		9:  "NOT_LOGIN_ERROR",
		10: "INVALID_TOKEN",
		11: "USER_NOT_FOUND",
		12: "NO_AUTH_ERROR",
	}
	ErrorReason_value = map[string]int32{
		"PARAMS_ERROR":                     0,
		"ACCOUNT_TOO_SHORT":                1,
		"PASSWORD_TOO_SHORT":               2,
		"PASSWORD_NOT_MATCH":               3,
		"ACCOUNT_DUPLICATE":                4,
		"SYSTEM_ERROR":                     5,
		"USER_NOT_EXIST_OR_PASSWORD_ERROR": 6,
		"ACCOUNT_ERROR":                    7,
		"PASSWORD_ERROR":                   8,
		"NOT_LOGIN_ERROR":                  9,
		"INVALID_TOKEN":                    10,
		"USER_NOT_FOUND":                   11,
		"NO_AUTH_ERROR":                    12,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_user_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_user_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_user_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_user_v1_error_reason_proto protoreflect.FileDescriptor

const file_user_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1auser/v1/error_reason.proto\x12\vapi.user.v1\x1a\x13errors/errors.proto*\xff\x02\n" +
	"\vErrorReason\x12\x16\n" +
	"\fPARAMS_ERROR\x10\x00\x1a\x04\xa8E\x90\x03\x12\x1b\n" +
	"\x11ACCOUNT_TOO_SHORT\x10\x01\x1a\x04\xa8E\x90\x03\x12\x1c\n" +
	"\x12PASSWORD_TOO_SHORT\x10\x02\x1a\x04\xa8E\x90\x03\x12\x1c\n" +
	"\x12PASSWORD_NOT_MATCH\x10\x03\x1a\x04\xa8E\x90\x03\x12\x1b\n" +
	"\x11ACCOUNT_DUPLICATE\x10\x04\x1a\x04\xa8E\x99\x03\x12\x16\n" +
	"\fSYSTEM_ERROR\x10\x05\x1a\x04\xa8E\xf4\x03\x12*\n" +
	" USER_NOT_EXIST_OR_PASSWORD_ERROR\x10\x06\x1a\x04\xa8E\x91\x03\x12\x17\n" +
	"\rACCOUNT_ERROR\x10\a\x1a\x04\xa8E\x90\x03\x12\x18\n" +
	"\x0ePASSWORD_ERROR\x10\b\x1a\x04\xa8E\x90\x03\x12\x19\n" +
	"\x0fNOT_LOGIN_ERROR\x10\t\x1a\x04\xa8E\x91\x03\x12\x17\n" +
	"\rINVALID_TOKEN\x10\n" +
	"\x1a\x04\xa8E\x91\x03\x12\x18\n" +
	"\x0eUSER_NOT_FOUND\x10\v\x1a\x04\xa8E\x94\x03\x12\x17\n" +
	"\rNO_AUTH_ERROR\x10\f\x1a\x04\xa8E\x93\x03\x1a\x04\xa0E\xf4\x03B;\n" +
	"\vapi.user.v1P\x01Z*smart-collab-gallery-server/api/user/v1;v1b\x06proto3"

var (
	file_user_v1_error_reason_proto_rawDescOnce sync.Once
	file_user_v1_error_reason_proto_rawDescData []byte
)

func file_user_v1_error_reason_proto_rawDescGZIP() []byte {
	file_user_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_user_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_error_reason_proto_rawDesc), len(file_user_v1_error_reason_proto_rawDesc)))
	})
	return file_user_v1_error_reason_proto_rawDescData
}

var file_user_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: api.user.v1.ErrorReason
}
var file_user_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_v1_error_reason_proto_init() }
func file_user_v1_error_reason_proto_init() {
	if File_user_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_error_reason_proto_rawDesc), len(file_user_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_user_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_user_v1_error_reason_proto_enumTypes,
	}.Build()
	File_user_v1_error_reason_proto = out.File
	file_user_v1_error_reason_proto_goTypes = nil
	file_user_v1_error_reason_proto_depIdxs = nil
}
