// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	"fmt"

	"github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the errors package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func ErrorParamsError(format string, args ...interface{}) *errors.Error {
	return errors.New(40000, "PARAMS_ERROR", fmt.Sprintf(format, args...))
}

func IsParamsError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == "PARAMS_ERROR" && e.Code == 40000
}

func ErrorSystemError(format string, args ...interface{}) *errors.Error {
	return errors.New(50000, "SYSTEM_ERROR", fmt.Sprintf(format, args...))
}

func IsSystemError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == "SYSTEM_ERROR" && e.Code == 50000
}

func ErrorFileTypeNotSupported(format string, args ...interface{}) *errors.Error {
	return errors.New(40003, "FILE_TYPE_NOT_SUPPORTED", fmt.Sprintf(format, args...))
}

func IsFileTypeNotSupported(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == "FILE_TYPE_NOT_SUPPORTED" && e.Code == 40003
}

func ErrorFileTooLarge(format string, args ...interface{}) *errors.Error {
	return errors.New(40004, "FILE_TOO_LARGE", fmt.Sprintf(format, args...))
}

func IsFileTooLarge(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == "FILE_TOO_LARGE" && e.Code == 40004
}
