// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: file/v1/error_reason.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	// 参数错误
	ErrorReason_PARAMS_ERROR ErrorReason = 0
	// 系统错误
	ErrorReason_SYSTEM_ERROR ErrorReason = 1
	// 文件类型不支持
	ErrorReason_FILE_TYPE_NOT_SUPPORTED ErrorReason = 2
	// 文件过大
	ErrorReason_FILE_TOO_LARGE ErrorReason = 3
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "PARAMS_ERROR",
		1: "SYSTEM_ERROR",
		2: "FILE_TYPE_NOT_SUPPORTED",
		3: "FILE_TOO_LARGE",
	}
	ErrorReason_value = map[string]int32{
		"PARAMS_ERROR":            0,
		"SYSTEM_ERROR":            1,
		"FILE_TYPE_NOT_SUPPORTED": 2,
		"FILE_TOO_LARGE":          3,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_file_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_file_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_file_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_file_v1_error_reason_proto protoreflect.FileDescriptor

const file_file_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1afile/v1/error_reason.proto\x12\vapi.file.v1\x1a\x13errors/errors.proto*b\n" +
	"\vErrorReason\x12\x10\n" +
	"\fPARAMS_ERROR\x10\x00\x12\x10\n" +
	"\fSYSTEM_ERROR\x10\x01\x12\x1b\n" +
	"\x17FILE_TYPE_NOT_SUPPORTED\x10\x02\x12\x12\n" +
	"\x0eFILE_TOO_LARGE\x10\x03B;\n" +
	"\vapi.file.v1P\x01Z*smart-collab-gallery-server/api/file/v1;v1b\x06proto3"

var (
	file_file_v1_error_reason_proto_rawDescOnce sync.Once
	file_file_v1_error_reason_proto_rawDescData []byte
)

func file_file_v1_error_reason_proto_rawDescGZIP() []byte {
	file_file_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_file_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_v1_error_reason_proto_rawDesc), len(file_file_v1_error_reason_proto_rawDesc)))
	})
	return file_file_v1_error_reason_proto_rawDescData
}

var file_file_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_file_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: api.file.v1.ErrorReason
}
var file_file_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_file_v1_error_reason_proto_init() }
func file_file_v1_error_reason_proto_init() {
	if File_file_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_v1_error_reason_proto_rawDesc), len(file_file_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_file_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_file_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_file_v1_error_reason_proto_enumTypes,
	}.Build()
	File_file_v1_error_reason_proto = out.File
	file_file_v1_error_reason_proto_goTypes = nil
	file_file_v1_error_reason_proto_depIdxs = nil
}
