// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.21.12
// source: file/v1/file.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationFileGetUploadPresignedUrl = "/api.file.v1.File/GetUploadPresignedUrl"

type FileHTTPServer interface {
	// GetUploadPresignedUrl 获取上传预签名 URL
	GetUploadPresignedUrl(context.Context, *GetUploadPresignedUrlRequest) (*GetUploadPresignedUrlReply, error)
}

func RegisterFileHTTPServer(s *http.Server, srv FileHTTPServer) {
	r := s.Route("/")
	r.POST("/api/file/upload/presigned", _File_GetUploadPresignedUrl0_HTTP_Handler(srv))
}

func _File_GetUploadPresignedUrl0_HTTP_Handler(srv FileHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUploadPresignedUrlRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFileGetUploadPresignedUrl)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUploadPresignedUrl(ctx, req.(*GetUploadPresignedUrlRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUploadPresignedUrlReply)
		return ctx.Result(200, reply)
	}
}

type FileHTTPClient interface {
	// GetUploadPresignedUrl 获取上传预签名 URL
	GetUploadPresignedUrl(ctx context.Context, req *GetUploadPresignedUrlRequest, opts ...http.CallOption) (rsp *GetUploadPresignedUrlReply, err error)
}

type FileHTTPClientImpl struct {
	cc *http.Client
}

func NewFileHTTPClient(client *http.Client) FileHTTPClient {
	return &FileHTTPClientImpl{client}
}

// GetUploadPresignedUrl 获取上传预签名 URL
func (c *FileHTTPClientImpl) GetUploadPresignedUrl(ctx context.Context, in *GetUploadPresignedUrlRequest, opts ...http.CallOption) (*GetUploadPresignedUrlReply, error) {
	var out GetUploadPresignedUrlReply
	pattern := "/api/file/upload/presigned"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationFileGetUploadPresignedUrl))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
