// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: file/v1/file.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取上传预签名 URL 请求
type GetUploadPresignedUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`          // 文件名（包含扩展名）
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // 文件 MIME 类型（可选）
	BucketName    string                 `protobuf:"bytes,3,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`    // 存储桶 key（如 image/video/document，可选，不传则自动检测）
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`                              // 地域（保留字段，暂未使用）
	UploadDir     string                 `protobuf:"bytes,5,opt,name=upload_dir,json=uploadDir,proto3" json:"upload_dir,omitempty"`       // 上传目录前缀（保留字段，暂未使用）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadPresignedUrlRequest) Reset() {
	*x = GetUploadPresignedUrlRequest{}
	mi := &file_file_v1_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadPresignedUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadPresignedUrlRequest) ProtoMessage() {}

func (x *GetUploadPresignedUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadPresignedUrlRequest.ProtoReflect.Descriptor instead.
func (*GetUploadPresignedUrlRequest) Descriptor() ([]byte, []int) {
	return file_file_v1_file_proto_rawDescGZIP(), []int{0}
}

func (x *GetUploadPresignedUrlRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *GetUploadPresignedUrlRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *GetUploadPresignedUrlRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *GetUploadPresignedUrlRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GetUploadPresignedUrlRequest) GetUploadDir() string {
	if x != nil {
		return x.UploadDir
	}
	return ""
}

// 获取上传预签名 URL 响应
type GetUploadPresignedUrlReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadUrl     string                 `protobuf:"bytes,1,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`     // 预签名上传 URL
	FileKey       string                 `protobuf:"bytes,2,opt,name=file_key,json=fileKey,proto3" json:"file_key,omitempty"`           // 文件在 COS 中的完整路径（key）
	AccessUrl     string                 `protobuf:"bytes,3,opt,name=access_url,json=accessUrl,proto3" json:"access_url,omitempty"`     // 上传成功后的访问 URL
	ExpireTime    int64                  `protobuf:"varint,4,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"` // 过期时间（Unix 时间戳）
	BucketName    string                 `protobuf:"bytes,5,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`  // 实际使用的存储桶 key（如 image/video/document）
	Region        string                 `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`                            // 实际使用的地域
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadPresignedUrlReply) Reset() {
	*x = GetUploadPresignedUrlReply{}
	mi := &file_file_v1_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadPresignedUrlReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadPresignedUrlReply) ProtoMessage() {}

func (x *GetUploadPresignedUrlReply) ProtoReflect() protoreflect.Message {
	mi := &file_file_v1_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadPresignedUrlReply.ProtoReflect.Descriptor instead.
func (*GetUploadPresignedUrlReply) Descriptor() ([]byte, []int) {
	return file_file_v1_file_proto_rawDescGZIP(), []int{1}
}

func (x *GetUploadPresignedUrlReply) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *GetUploadPresignedUrlReply) GetFileKey() string {
	if x != nil {
		return x.FileKey
	}
	return ""
}

func (x *GetUploadPresignedUrlReply) GetAccessUrl() string {
	if x != nil {
		return x.AccessUrl
	}
	return ""
}

func (x *GetUploadPresignedUrlReply) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *GetUploadPresignedUrlReply) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *GetUploadPresignedUrlReply) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

var File_file_v1_file_proto protoreflect.FileDescriptor

const file_file_v1_file_proto_rawDesc = "" +
	"\n" +
	"\x12file/v1/file.proto\x12\vapi.file.v1\x1a\x1cgoogle/api/annotations.proto\"\xb6\x01\n" +
	"\x1cGetUploadPresignedUrlRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x1f\n" +
	"\vbucket_name\x18\x03 \x01(\tR\n" +
	"bucketName\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x1d\n" +
	"\n" +
	"upload_dir\x18\x05 \x01(\tR\tuploadDir\"\xcf\x01\n" +
	"\x1aGetUploadPresignedUrlReply\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x01 \x01(\tR\tuploadUrl\x12\x19\n" +
	"\bfile_key\x18\x02 \x01(\tR\afileKey\x12\x1d\n" +
	"\n" +
	"access_url\x18\x03 \x01(\tR\taccessUrl\x12\x1f\n" +
	"\vexpire_time\x18\x04 \x01(\x03R\n" +
	"expireTime\x12\x1f\n" +
	"\vbucket_name\x18\x05 \x01(\tR\n" +
	"bucketName\x12\x16\n" +
	"\x06region\x18\x06 \x01(\tR\x06region2\x9b\x01\n" +
	"\x04File\x12\x92\x01\n" +
	"\x15GetUploadPresignedUrl\x12).api.file.v1.GetUploadPresignedUrlRequest\x1a'.api.file.v1.GetUploadPresignedUrlReply\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/file/upload/presignedB;\n" +
	"\vapi.file.v1P\x01Z*smart-collab-gallery-server/api/file/v1;v1b\x06proto3"

var (
	file_file_v1_file_proto_rawDescOnce sync.Once
	file_file_v1_file_proto_rawDescData []byte
)

func file_file_v1_file_proto_rawDescGZIP() []byte {
	file_file_v1_file_proto_rawDescOnce.Do(func() {
		file_file_v1_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_file_v1_file_proto_rawDesc), len(file_file_v1_file_proto_rawDesc)))
	})
	return file_file_v1_file_proto_rawDescData
}

var file_file_v1_file_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_file_v1_file_proto_goTypes = []any{
	(*GetUploadPresignedUrlRequest)(nil), // 0: api.file.v1.GetUploadPresignedUrlRequest
	(*GetUploadPresignedUrlReply)(nil),   // 1: api.file.v1.GetUploadPresignedUrlReply
}
var file_file_v1_file_proto_depIdxs = []int32{
	0, // 0: api.file.v1.File.GetUploadPresignedUrl:input_type -> api.file.v1.GetUploadPresignedUrlRequest
	1, // 1: api.file.v1.File.GetUploadPresignedUrl:output_type -> api.file.v1.GetUploadPresignedUrlReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_file_v1_file_proto_init() }
func file_file_v1_file_proto_init() {
	if File_file_v1_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_file_v1_file_proto_rawDesc), len(file_file_v1_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_file_v1_file_proto_goTypes,
		DependencyIndexes: file_file_v1_file_proto_depIdxs,
		MessageInfos:      file_file_v1_file_proto_msgTypes,
	}.Build()
	File_file_v1_file_proto = out.File
	file_file_v1_file_proto_goTypes = nil
	file_file_v1_file_proto_depIdxs = nil
}
