// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"smart-collab-gallery-server/internal/biz"
	"smart-collab-gallery-server/internal/conf"
	"smart-collab-gallery-server/internal/data"
	"smart-collab-gallery-server/internal/server"
	"smart-collab-gallery-server/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(bootstrap, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo, logger)
	jwtManager := service.NewJWTManager(bootstrap)
	userService := service.NewUserService(userUsecase, jwtManager, logger)
	pictureRepo := data.NewPictureRepo(dataData, logger)
	pictureUsecase := biz.NewPictureUsecase(pictureRepo, userRepo, logger)
	pictureService := service.NewPictureService(pictureUsecase, logger)
	healthService := service.NewHealthService()
	grpcServer := server.NewGRPCServer(bootstrap, greeterService, userService, healthService, logger)
	cosManager, err := service.NewCOSManager(bootstrap, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	fileService := service.NewFileService(cosManager, logger)
	httpServer := server.NewHTTPServer(bootstrap, greeterService, userService, fileService, pictureService, healthService, jwtManager, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
